name: Integración continua (api)

on:
  push:
    branches: [ main ]
    paths: ['hangman-api/**']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build and test
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18
      - name: Unit tests
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run test
  bye:
    runs-on: ubuntu-latest
    #if: always() # para que se ejecute aunque falle el job de test
    needs: test
    steps:
      - name: bye
        run: echo "bye!"
